### ISSUE TITLE
So what page is this supposed to go?

### ISSUE THREAD

**Issue by mudrd8mz** [SergioComeron/moodle-block-common_courses#2]
From the description, I understood this block is aimed at being present on user's profile pages. So I would expect the `applicable_formats()` returns something like `user-profile`. How does it help to allow adding the block to the frontpage only?

**Comment by SergioComeron** [comment]
Hello david,
I make it this way because in our organization we wanted the block to come out both in the user-profile and in the profile that is accessed from a course.
If I put in the applicable-formats only user-profile I could get it in the profile but not in the one I access from a course (which is from the user view). so what I did is that I show it everywhere and then I hide it by css.
Maybe to publish in the repository the best thing is to leave it alone in the user-profile.
Or is possible a way to make the applicable-formats so that it appears in the normal user-profile and the profile as it is accessed from a course?
There are two different types of profile:
normal user-profile: http: //localhost/moodle/user/profile.php?id=3
user-profile from a course: http: //localhost/moodle/user/view.php?id=3&course=3

**Comment by mudrd8mz** [comment]
I understand that use case and it makes sense. I just think it could be done in a "cleaner" way without the need for CSS hacks. Please refer to https://docs.moodle.org/35/en/Block_settings#.27Sticky_blocks.27 and https://docs.moodle.org/35/en/User_profiles#Default_profile_page

**Comment by mudrd8mz** [comment]
And what if the `applicable_formats()` returns both? Something like
```
return ['user-view' => true, 'user-profile' => true];
```

**Comment by SergioComeron** [comment]
Hi, it's a good idea but with user-view => true I haven't been able to add the block in the profile 'user-view'.

**Comment by SergioComeron** [comment]
the way you suggest would make it also view on the course page. 
for this we would have to use course-view-weeks => true (for example) in the applicable_formats and this also shows it on the course page.

I'll keep thinking about this to see how I can do it cleanly

**Comment by SergioComeron** [comment]
ok, it really would not be a problem because the block on the course page is never going to be seen.
I think it's a good solution. I will do so in the next version.

**Comment by SergioComeron** [comment]
finally the idea isn't valid because an administrator can't put the block in all the "course profile" :(
The new version applicable_formats is for all.

**Comment by mudrd8mz** [comment]
Hmm, you're right. It's not easy. Normally it works that you put the block to the front page and then let it display on a user profile page types only. But this can't be achieved as we effectively have two different places with very similar content (user profile). It would work on one or another, but not both. In either case, the user must be able to add the block to the front page.

**Comment by SergioComeron** [comment]
solved on new version
